### ISSUE TITLE
Bootstrap causes the editor to move very slowly

### ISSUE THREAD

**Issue by johnotander** [johnotander/immutable-css#11]
Might need to cache the immutable css class list or something to speed performance. Another potential solution is to add a timeout to the change event so that the entire immutability check isn't run on every editor change.

**Comment by johnotander** [comment]
For the time being, we will be removing the live editing functionality.

**Comment by jxnblk** [comment]
Fwiw I've been experimenting with the speed of live editing and think that using lodash's throttle for the demo seems to work. Will have something to share soon.

**Comment by johnotander** [comment]
:heart_eyes_cat:
