### ISSUE TITLE
Check for mutations in a directory or glob

### ISSUE THREAD

**Issue by johnotander** [johnotander/immutable-css#12]
It'd be awesome (at least I think so) to be able to check for mutations in CSS files that are in a directory, either passing a directory or a glob. `immutable-css` would then ensure that a class isn't mutated in more than one file.

Perhaps, something like:

```js
immutableCss('src/css/**/*.css')
// => [{
//   class: '.button',
//   mutatingFiles: [
//     'src/css/buttons.css',
//     'src/css/components/some-file-that-should-not-mutate-button.css'
//   ]
// }]
```

Thoughts @jxnblk ?

**Comment by jxnblk** [comment]
Love it. That's actually a really awesome idea. :+1: 

Would you still pass the vendor/source as the first argument?

**Comment by johnotander** [comment]
Cools! Ah, yes, forgot to add the vendor argument in the proposed example.

**Comment by fmal** [comment]
Would love to see this feature merged :+1:

**Comment by johnotander** [comment]
See #14
