### ISSUE TITLE
Fail reporter

### ISSUE THREAD

**Issue by winkerVSbecks** [johnotander/immutable-css#24]
First off, this is an awesome tool! Thank you for building and maintaining it. 

I am looking to use this a part of our CI setup. Essentially every PR has to go through automated testing and linting before it can be merged. This requires the lint and test tools to report failures to break the build. I believe this is essentially done by throwing JS errors instead of `console.log`.

Any chance this could be added as a feature? Thanks

**Comment by johnotander** [comment]
Glad you like it.

This feature definitely could, and should, be added. I believe it is as simple as exiting with the error code, `1`. I'll get to this in the next couple hours. I'll keep you posted.

**Comment by winkerVSbecks** [comment]
That's awesome! Thank you again

**Comment by johnotander** [comment]
My pleasure, thanks for creating the issue : )
