### ISSUE TITLE
Promotional/docs page with client side demo

### ISSUE THREAD

**Issue by johnotander** [johnotander/immutable-css#9]
- [x] Write documentation with a description of "immutable CSS"
- [x] Promote the ideas/benefits of CSS
- [x] Build with Basscss
- [x] Use browserify to check for mutations
- [x] Gulp build for concat/min/uncss/inline CSS

**Comment by jxnblk** [comment]
Aww yis.

**Comment by johnotander** [comment]
:)

**Comment by johnotander** [comment]
@jxnblk did you want to take a stab at this? I know you mentioned it earlier.

**Comment by jxnblk** [comment]
Yeah unless you want to. Was wanting to take a stab this weekend. Any guidance on the client side js would be much appreciated though.

**Comment by johnotander** [comment]
You'd do a way better job than I could _ever_ do with the information architecture and styling. I'd be so stoked if you wanted to run with it, your skills are legion . I'd be glad to help with getting the client side js together.

I'd imagine we can run `immutable-css` on the client with `browserify`, similarly to how https://github.com/johnotander/rework-flex-grid/tree/gh-pages works. The majority of the js dependencies will be the same (I think?). The js should run absurdly quickly, so you can likely run the entire `immutable-css` function on every input change or perhaps when an "do the work" button is clicked. If you want me to get a basic client side, raw HTML prototype together for you to build off of, let me know.

Ping me here, via twitter, or via email if I can be of assistance with anything. So pumped to see what you come up with <3.

**Comment by jxnblk** [comment]
Wow! I just noticed rework-flex-grid the other day – rad stuff.

I think you should definitely handle the client side js if you have time. I'll try to get some draft copy/rough layout ideas together in the next day or two.

**Comment by johnotander** [comment]
I've got some time today, so I'll whip something up.

**Comment by johnotander** [comment]
Just got a foobar version going in the gh-pages branch: http://johnotander.com/immutable-css/

Needs a bunch of love, but it has `immutable-css` running on the client with two text areas (first for lib/immutable css, second for app css).

**Comment by jxnblk** [comment]
Rad. This is exactly what I was looking for.

A (potentially crazy) thought just occurred to me while I was in a meeting: would it be possible/easy to have the app css textarea show line numbers and highlight the mutated selectors (or lines) with the warnings inline? For example: the app css text area would be the main focus of the demo app and the results/warnings show in context – or maybe the warnings are split up like how GitHub shows code snippets next to conversations in pull requests.

I know that there's things out there like codemirror, but I'm guessing that might be overkill for this.

**Comment by johnotander** [comment]
That's an awesome idea. I'll fiddle around a bit this afternoon and see if I can get something together with either codemirror or ace.

**Comment by johnotander** [comment]
Got a _super_ basic editor working that reports an error in the gutter: http://johnotander.com/immutable-css/editor Currently the immutable.css that's being compared to is:

```css
.foo { color: red; }
```

So, only `.foo` classes in the CSS will cause an error. I imagine we will want some way to toggle between popular libraries, and inputting custom immutable CSS.

**Comment by jxnblk** [comment]
Heyo,

Taking a stab at prototyping what this could look like on another branch for the moment – mostly to get feedback from you: https://github.com/johnotander/immutable-css/tree/promo-page-prototype

Let me know what you think about this general direction.

Things to note:
- The HTML structure is pretty sloppy but just threw things in to test out visuals. Will definitely clean that up.
- The copy and labels are really rough. I'm struggling with what to call the _immutable css_ and the _app specific_/_custom_ css.
- The responsiveness is goofy at the moment (footer shows above the main panel at small widths)
- When selecting Bootstrap to check against, things start to feel sluggish on my 11" Air
- Wondering how we should handle the "frameworks" css – should we have a task that copies CSS from bower/npm into a folder that gets checked in or what?

I'll probably need some help with the Ace editor. I was imagining having a warning div next to or above/below the line with the mutation. It would be nice to avoid positioning if possible.

If the Ace editor doesn't make sense for this demo site, maybe the app css can be a basic text area with the warnings listed below with readonly highlighted code snippets...

![2015-04-05 15 16 35](https://cloud.githubusercontent.com/assets/3451712/6998224/3c73fcc6-dba7-11e4-87c1-55729554f066.jpg)

**Comment by jxnblk** [comment]
Oh, and I _think_ the submit button isn't working with Ace editor.

**Comment by johnotander** [comment]
This looks absolutely amazing! So pumped. :confetti_ball: :confetti_ball: :confetti_ball: 

I really don't have any feedback for you, you made it look way better than I could've ever imagined. I think the only part that seems to be missing is some type of why/about page which perhaps describes why immutable css is a good idea, and how it can result in more scalable css (this could potentially be a "learn more" link or something under the title and descriptive blurb).

> If the Ace editor doesn't make sense for this demo site, maybe the app css can be a basic text area with the warnings listed below with readonly highlighted code snippets...

I wonder if there should be two error display contexts? One that is editor-esque with error information in the editor, and the other that is a "report" (similar to the sketch that you included). Perhaps each in their own tab. Though, the "check for mutations" buttons could go the report mode, with the ability to toggle back to the editor (since the editor should be perpetually live updating any mutations as the editor content changes already).

> The copy and labels are really rough. I'm struggling with what to call the immutable css and the app specific/custom css.

I've been pondering that as well, but I, too, haven't been successful in coming up with naming. immutable/app, immutable/custom, vendor/app, library/app etc.

> Wondering how we should handle the "frameworks" css – should we have a task that copies CSS from bower/npm into a folder that gets checked in or what?

Yeah, I think that'd be the best way to handle it.

> I'll probably need some help with the Ace editor. I was imagining having a warning div next to or above/below the line with the mutation. It would be nice to avoid positioning if possible.

I'll try and get a raw implementation together this afternoon.

> Oh, and I think the submit button isn't working with Ace editor.

Correct, the submit button is currently not working with the editor. Didn't bind to it during my haste, I will be sure to fix that.

Really excited to see this take shape, so cool.

**Comment by johnotander** [comment]
I'm having a bit of trouble injecting a warning div into the ace editor. However, I was able to add an ace "annotation" that we could potentially customize (its defaults are not very pretty and I'm not sure how mobile friendly it is since its based on :hover :frowning:) as well. See it in action: http://johnotander.com/immutable-css/

**Comment by johnotander** [comment]
Also, the check mutations button is now working again, it just spews the raw data into the DOM currently.

**Comment by jxnblk** [comment]
Hey, sorry for the delay (got a little distracted...) – gonna pick this back up today.

I think going with the static list as the primary view is a stronger way to go for now. We can keep the editor as a secondary view (maybe behind a tab), but that annotation thing is kind of meh :stuck_out_tongue_winking_eye:

**Comment by johnotander** [comment]
No worries :smile_cat:.

Yeah, I think you're right on that front, the editor should become a secondary view. The annotations are definitely quite meh. From my experimentation I was unable to leverage ace.js the way we'd like to display error messages in the editor. So, for now I can revert back to the gutter coloring to indicate errors.

**Comment by jxnblk** [comment]
I think you can leave what you have for now.

I got in the weeds exploring contentEditable pre tags, so not sure that I have that much to show yet.
I *think* it's helping me explore some ideas though, so stay tuned.

**Comment by johnotander** [comment]
This can now be closed, thanks to @jxnblk
